### ISSUE TITLE
有没有api文档呢

### ISSUE THREAD

**Issue by acrossTheGreatWall1024** [jwwam/tourismPro#2]

**Comment by acrossTheGreatWall1024** [comment]
Mysql 5.7.29版本可能在后台管理页面IndexData显示错误，在msql中执行SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY','')); 可以解决

https://stackoverflow.com/questions/41887460/select-list-is-not-in-group-by-clause-and-contains-nonaggregated-column-inc/41887627#41887627?newreg=a2815bf7a27c4311964a540d213767ad

**Comment by Cercis-chinensis** [comment]
同求
